apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: bind-secret
  namespace: secure-space
subjects:
  - kind: ServiceAccount
    name: security-officer
    namespace: secure-space
roleRef:
  kind: Role
  name: role-secret
  apiGroup: rbac.authorization.k8s.io
